name: agenticdoc
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/ryanam26/agenticdoc.git
    build_command: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-dev
    run_command: |
      poetry run uvicorn webapp.app:app --host 0.0.0.0 --port $PORT
    envs:
      - key: PORT
        value: "8080"
      - key: ENVIRONMENT
        value: "production"
      - key: VISION_AGENT_API_KEY
        value: "${VISION_AGENT_API_KEY}"
      - key: SUPABASE_URL
        value: "${SUPABASE_URL}"
      - key: SUPABASE_SERVICE_ROLE_KEY
        value: "${SUPABASE_SERVICE_ROLE_KEY}"
      - key: AGENTIC_DOC_URL
        value: "${AGENTIC_DOC_URL}"
      - key: OPENAI_API_KEY
        value: "${OPENAI_API_KEY}"
      - key: MAX_RETRIES
        value: "10"
      - key: MAX_RETRY_WAIT_TIME
        value: "30"
    instance_size_slug: apps-s-1vcpu-1gb-fixed
    instance_count: 1
    http_port: 8080
    source_dir: /
