name: agenticdoc-api
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/ryanam26/agenticdoc.git
    build_command: |
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-dev
    run_command: |
      poetry run uvicorn webapp.app:app --host 0.0.0.0 --port $PORT
    envs:
      - key: PORT
        value: "8080"
      - key: ENVIRONMENT
        value: "production"
      - key: VISION_AGENT_API_KEY
        value: "${VISION_AGENT_API_KEY}"
    instance_size_slug: basic-xxs
    instance_count: 1
