name: agenticdoc-api
services:
  - name: web
    git:
      branch: main
      repo_clone_url: https://github.com/ryanam26/agenticdoc.git
    build_command: pip install -r requirements.txt
    run_command: uvicorn src.agenticdoc.webapp.app:app --host 0.0.0.0 --port $PORT
    envs:
      - key: PORT
        value: "8080"
      - key: ENVIRONMENT
        value: "production"
    instance_size_slug: basic-xxs
    instance_count: 1 